### PR TITLE
Added LightSensor and TemperatureSensor implementations

### PR DESCRIPTION
**Pull request by VladVin**

### CODE REVIEW

**Comment by VladVin** [comment]
@RuslanIsrafilov , review, please

**Comment by RuslanIsrafilov** [comment]
You create new instance of grove sensor class (for example GroveLight) in `state` method. It's not effective. Method `state` calls periodically. You should create instance in your class constructor.

**Comment by VladVin** [comment]
@RuslanIsrafilov , I know, of course, but my Python skills are poor and I didn't it :) Ok, I will fix it.

**Comment by RuslanIsrafilov** [comment]
@VladVin, please create new branch (for example sensors-impl) and working with it.

**Comment by RuslanIsrafilov** [comment]
@VladVin, please configure git.
capture

**Comment by VladVin** [comment]
@RuslanIsrafilov , why not 'vlad-vin' branch?

**Comment by RuslanIsrafilov** [comment]
@VladVin, this name is not representational. Branch, as rule, need to implement certain feature. In you case sensors implementation.

**Comment by VladVin** [comment]
@RuslanIsrafilov , see [new PR](https://github.com/iss2015-iot/iot-sensors-broadcast/pull/2)

**Pull request closed without merging**
